# Question 2.3a
@prefix : <http://www.exemple.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix sh: <http://www.w3.org/ns/shacl#> .

:PersonShape
	a sh:NodeShape;
	sh:targetClass :Person;
	sh:property [
		sh:path rdfs:label;
		sh:datatype xsd:string;
	].